# Generated by Django 5.1.1 on 2025-04-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0006_alter_student_trieda_alter_ucitel_trieda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kruzok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('skratka', models.CharField(max_length=10)),
                ('ucitel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skola.ucitel')),
            ],
            options={
                'verbose_name': 'Krúžok',
                'verbose_name_plural': 'Krúžky',
                'ordering': ['nazov'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='kruzok',
            field=models.ManyToManyField(blank=True, to='skola.kruzok'),
        ),
    ]
